@echo off

if not exist "%TEMPORARY_DOWNLOAD_DIRECTORY%" mkdir "%TEMPORARY_DOWNLOAD_DIRECTORY%"

if exist "%INSTALLER_GIT%" goto END

set DOWNLOAD_DESTINATION=%TEMPORARY_DOWNLOAD_DIRECTORY%\%INSTALLER_GIT%
set TRANSFER_LOCATION=%INSTALLER_GIT%

if exist "%TEMPORARY_DOWNLOAD_DIRECTORY%\%INSTALLER_GIT%" goto RESOLVE_GIT_PATH

echo Downloading Git installer.

set JOB_ID=%DOWNLOAD_GIT_JOB_ID%
set DOWNLOAD_URL=%DOWNLOAD_URL_GIT%

call download.bat

:RESOLVE_GIT_PATH
if exist "%TRANSFER_LOCATION%" goto END
move "%DOWNLOAD_DESTINATION%" "%TRANSFER_LOCATION%" > nul

rd /s /q %TEMPORARY_DOWNLOAD_DIRECTORY%

:END
if exist "%INSTALLER_GIT%" echo Git installer has been downloaded.