@echo off

if not exist "%TEMPORARY_DOWNLOAD_DIRECTORY%" mkdir "%TEMPORARY_DOWNLOAD_DIRECTORY%"

if exist "%INSTALLER_NODEJS%" goto END

set DOWNLOAD_DESTINATION=%TEMPORARY_DOWNLOAD_DIRECTORY%\%INSTALLER_NODEJS%
set TRANSFER_LOCATION=%INSTALLER_NODEJS%

if exist "%TEMPORARY_DOWNLOAD_DIRECTORY%\%INSTALLER_NODEJS%" goto RESOLVE_NODEJS_PATH

set JOB_ID=%DOWNLOAD_NODEJS_JOB_ID%

if "%PLATFORM_ARCHITECTURE%"=="%BIT32%" ( 	
	echo Downloading 32-bit NodeJS installer.
	set DOWNLOAD_URL=%DOWNLOAD_URL_NODEJS_32BIT%
) else (
	echo Downloading 64-bit NodeJS installer.
	set DOWNLOAD_URL=%DOWNLOAD_URL_NODEJS_64BIT%
)

call download.bat

:RESOLVE_NODEJS_PATH
if exist "%TRANSFER_LOCATION%" goto END
move "%DOWNLOAD_DESTINATION%" "%TRANSFER_LOCATION%" > nul

rd /s /q %TEMPORARY_DOWNLOAD_DIRECTORY%

:END
if exist "%INSTALLER_NODEJS%" echo NodeJS installer has been downloaded.