@echo off
if not exist %TEMPORARY_DOWNLOAD_DIRECTORY% mkdir %TEMPORARY_DOWNLOAD_DIRECTORY%

if EXIST "%TEMPORARY_DOWNLOAD_DIRECTORY%/7zip.exe" goto RESOLVE_7ZIP_EXECUTABLE_PATH
if EXIST "%TEMPORARY_DOWNLOAD_DIRECTORY%/7zip.msi" goto RESOLVE_7ZIP_EXECUTABLE_PATH
if "%PLATFORM_ARCHITECTURE%"=="%BIT32%" ( 	
	echo Downloading 32-bit 7-Zip executable installer.
	set JOB_ID=%DOWNLOAD_7ZIP_32BIT_JOB_ID%
	set DOWNLOAD_URL=%DOWNLOAD_URL_7ZIP_32BIT%
	set DOWNLOAD_DESTINATION="%TEMPORARY_DOWNLOAD_DIRECTORY%/7zip.exe"
	set TRANSFER_LOCATION=%INSTALLER_7ZIP_32BIT%
) else (
	echo Downloading 64-bit 7-Zip executable installer.
	set JOB_ID=%DOWNLOAD_7ZIP_64BIT_JOB_ID%
	set DOWNLOAD_URL=%DOWNLOAD_URL_7ZIP_64BIT%
	set DOWNLOAD_DESTINATION="%TEMPORARY_DOWNLOAD_DIRECTORY%/7zip.msi"
	set TRANSFER_LOCATION=%INSTALLER_7ZIP_64BIT%
)
call download.bat

:RESOLVE_7ZIP_EXECUTABLE_PATH
if EXIST "%TRANSFER_LOCATION%" goto DOWNLOAD_7ZIP_COMMAND_LINE
move "%DOWNLOAD_DESTINATION%" "%TRANSFER_LOCATION%"

:DOWNLOAD_7ZIP_COMMAND_LINE
if EXIST "%TEMPORARY_DOWNLOAD_DIRECTORY%/7za.zip" goto RESOLVE_7ZIP_COMMAND_LINE_PATH
echo Downloading 32-bit 7-Zip command line tool.
set JOB_ID=%DOWNLOAD_7ZIP_COMMAND_LINE_JOB_ID%
set DOWNLOAD_URL=%DOWNLOAD_URL_7ZIP_COMMAND_LINE%
set DOWNLOAD_DESTINATION="%TEMPORARY_DOWNLOAD_DIRECTORY%/7za.zip"
set TRANSFER_LOCATION=%COMMAND_LINE_7ZIP_32BIT%
call download.bat

:RESOLVE_7ZIP_COMMAND_LINE_PATH
if EXIST "%TRANSFER_LOCATION%" goto END
move "%DOWNLOAD_DESTINATION%" "%TRANSFER_LOCATION%"

:END
rd /s /q %TEMPORARY_DOWNLOAD_DIRECTORY%
